// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeYB-yKTasDiUF_iwTV4xAbBcq0xBiTnY',
    appId: '1:315702581395:web:84f6aec561611cf8aed566',
    messagingSenderId: '315702581395',
    projectId: 'quickmessaging-e9dde',
    authDomain: 'quickmessaging-e9dde.firebaseapp.com',
    storageBucket: 'quickmessaging-e9dde.firebasestorage.app',
    measurementId: 'G-FE60FZJJNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIj0wbuP4HU-ehSkE2zQDWJU6qjoqI1vU',
    appId: '1:315702581395:android:abc2a6268317806baed566',
    messagingSenderId: '315702581395',
    projectId: 'quickmessaging-e9dde',
    storageBucket: 'quickmessaging-e9dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhsYWH9fuyBm8Q1rZ49PEsyx-fHoC0Seg',
    appId: '1:315702581395:ios:3473140b77b29756aed566',
    messagingSenderId: '315702581395',
    projectId: 'quickmessaging-e9dde',
    storageBucket: 'quickmessaging-e9dde.firebasestorage.app',
    iosBundleId: 'com.example.quickmsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhsYWH9fuyBm8Q1rZ49PEsyx-fHoC0Seg',
    appId: '1:315702581395:ios:3473140b77b29756aed566',
    messagingSenderId: '315702581395',
    projectId: 'quickmessaging-e9dde',
    storageBucket: 'quickmessaging-e9dde.firebasestorage.app',
    iosBundleId: 'com.example.quickmsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeYB-yKTasDiUF_iwTV4xAbBcq0xBiTnY',
    appId: '1:315702581395:web:8acc08f211752b73aed566',
    messagingSenderId: '315702581395',
    projectId: 'quickmessaging-e9dde',
    authDomain: 'quickmessaging-e9dde.firebaseapp.com',
    storageBucket: 'quickmessaging-e9dde.firebasestorage.app',
    measurementId: 'G-SWDW2EXSZL',
  );
}
